
import { GoogleGenAI } from "@google/genai";

if (!process.env.API_KEY) {
  console.warn("API_KEY environment variable not set. Gemini features will be disabled.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY! });

interface ImageGenerationParams {
  date: string;
  attendancePercentage: number;
  presentCount: number;
  absentCount: number;
  topStudents: string[];
  presentStudents: string[];
}

export const generateAttendanceImage = async ({
  date,
  attendancePercentage,
  presentCount,
  absentCount,
  topStudents,
  presentStudents,
}: ImageGenerationParams): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API key is not configured.");
  }
  
  const prompt = `
    Generate a visually appealing, clean, and modern infographic for a daily attendance report. The design should be minimalist, inspired by Apple's design language, with a dark theme. The image must be in a 9:16 aspect ratio.

    The image must contain the following elements, arranged logically and elegantly:

    1.  **Header:**
        *   Main Title: "Daily Attendance Summary" in a large, bold font.
        *   Date: "${date}" in a smaller, medium-weight font below the title.

    2.  **Key Statistics (prominently displayed in a row):**
        *   A large number "${attendancePercentage}%" with the label "Attendance".
        *   A large number "${presentCount}" with the label "Present".
        *   A large number "${absentCount}" with the label "Absent".

    3.  **Visual Element:**
        *   A simple, elegant donut chart representing the attendance percentage (${attendancePercentage}% filled). Use a vibrant green for 'Present' and a muted gray for 'Absent'.

    4.  **Top Performers Section:**
        *   Title: "Most Consistent Students"
        *   A numbered list of the top students:
            ${topStudents.map((name, i) => `${i + 1}. ${name}`).join('\n            ')}

    5.  **Main List Section:**
        *   Title: "Present Students"
        *   A numbered list of all present students:
            ${presentStudents.map((name, i) => `${i + 1}. ${name}`).join('\n            ')}

    6.  **Footer:**
        *   App Logo: The word "Attend" in a clean, sans-serif font.
        *   Credit: "Crafted by Amaan Shaik" in small text.

    The color palette must be a pitch-black background (#000000), white text, and a single accent color of bright green (#34C759) for highlights and the chart. Use a clear, legible sans-serif font like SF Pro or Inter. Ensure ample white space for a clean, uncluttered look.
  `;

  try {
    const response = await ai.models.generateImages({
      model: 'imagen-3.0-generate-002',
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/png',
        aspectRatio: '9:16',
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error generating image with Gemini API:", error);
    throw new Error("Failed to generate attendance summary image.");
  }
};
